Make URLs Lowercase Before Sending Request
miraheze/RottenLinks pull request #34
Opened 2021-06-03 13:05 UTC by R4356th

People sometimes forget to use lowercase characters in the protocol which makes RottenLinks grumpy. This simple change makes it so that the URL is made lowercase before sending the request to check a URL. See https://snapwiki.miraheze.org/wiki/Special:RottenLinks?showBad=1&limit=50 where ``Https://GitHub.com`` has been detected to be a "rotten" URL.

2021-06-03 13:21 UTC, dmehus commented
This seems like a reasonable and useful change to me. What about cases where capital letters are intentional or otherwise case sensitive? That would be my only concern, though this would have more to do with the //end// of the URL rather than the //start// (i.e., `SomePage.html` or `Special:RottenLinks`).

2021-06-03 13:25 UTC, R4356th commented
Great point, thanks. I believe RL won't be angry if the protocol is lowercase but the other part is upper based on my experience fixing these links.

2021-06-03 15:20 UTC, RhinosF1 requested changes
Syntax

2021-06-03 15:21 UTC, R4356th commented
> 
> 
> Syntax

Yeah, I made a typo while copying over from my local version. Fixed now.

2021-06-05 01:10 UTC, Universal-Omega requested changes

2021-06-05 01:10 UTC, Universal-Omega commented on includes/RottenLinks.php
> +		$urltouse = $proto . $site;
camelCase - `$urlToUse

2021-06-05 01:12 UTC, Universal-Omega commented
Also please add to CHANGELOG and do version bump

2021-06-05 07:14 UTC, R4356th commented on includes/RottenLinks.php
> +		$urltouse = $proto . $site;
Done.

2021-06-05 07:17 UTC, Universal-Omega commented on includes/RottenLinks.php
> +		$urltouse = $proto . $site;
Thanks!

2021-06-05 07:21 UTC, Universal-Omega approved these changes

2021-06-05 07:21 UTC, merged